<?php 
$this->headTitle('Demo Mode');
$this->headLink()->appendStylesheet($this->ServerUrl()."/layouts/skylable/css/pagedialog.css");
?>
<div class="dialog-box">
    <div class="dialog-box-logo">
        <span class="dialog-box-logo-icon ir"></span><h1><?php echo $this->translate('This is a demo!'); ?></h1>        
    </div>
    <div class="dialog-box-body">
        <h1><?php echo $this->translate('SXWeb is running in demo mode.'); ?></h1>
        <p><?php echo $this->translate('Some functionality are removed or not usable.'); ?></p>
        <p><?php echo $this->translate('Please upgrade to a normal version.'); ?></p>
        <div class="dialog-box-buttons">
            <a class="styled-button" href="/index" title="<?php echo $this->translate('Go to the home page...'); ?>"><?php echo $this->translate('Thank you!'); ?></a>
        </div>
    </div>
    <?php echo $this->render('index/messages.phtml'); ?>
</div>
