<?php
	$sxshare_address = Zend_Registry::get('skylable')->get('sxshare_address');
	$volume_is_encrypted = $this->volumeIsEncrypted( My_Utils::getRootFromPath( $this->url ) );
?>
<div class="sticked">
	<div class="wrap">
	<?php echo $this->render('index/messages.phtml'); ?>
        <?php echo $this->putMessage(); ?>
	<div id="search" >
		<form action="<?php echo $this->ServerUrl(); ?>/search,<?php echo $this->escape(My_Utils::getRootFromPath($this->url));?>" method="get" >
			<input type="submit" class="ir icon-search"  />
			<input type="search" placeholder="<?php echo $this->translate('Search...'); ?>" class="search" name="q"  />
		</form>
		<hr />		
	</div>
	<hr />
        <p class="bread-crumbs"><?php if($this->user_can_manage_volume): ?><a href="<?php echo $this->serverUrl('/settings/volume'),'?volume=',rawurlencode($this->url); ?>" title="<?php echo $this->translate('Manage the volume'); ?>"><span class="ir icon-bc-settings"></span></a> <?php endif;?><?php echo $this->breadcrumbs($this->url);?></p>
		<div class="bulk-actions">
			<?php if($this->canWriteToVolume()): ?>
			<ul>
				<li><?php echo $this->translate('Bulk Actions'); ?></li>
				<li><a class="share-trigger"  id="actioncopy"   ><?php echo $this->translate('Copy'); ?></a></li>
				<li><a class="move-trigger"   id="actionmove"   ><?php echo $this->translate('Move'); ?></a></li>
				<li><a class="delete-trigger" id="actiondelete" ><?php echo $this->translate('Delete'); ?></a></li>
			</ul>
			<?php endif; ?>
		</div>
		<div class="default-actions">
			<?php if($sxshare_address and !$volume_is_encrypted): ?>
			<a id="sharedir">
				<span><?php echo $this->translate('Share Folder'); ?></span>
			</a>
			<?php endif; ?>
			<?php if($this->canWriteToVolume()): ?>
			<a class="add-folder create-trigger" id="createdir" >
				<span class="icon-add-folder ir"></span>
				<span><?php echo $this->translate('New Folder'); ?></span>
			</a>
			<a class="upload" id="addfile" >
				<span class="icon-upload ir"></span>
				<span><?php echo $this->translate('Upload'); ?></span>
			</a>
			<?php endif; ?>
		</div>
		<p class="table-title">
			<span class="name"><a href="?sort=<?php echo ($this->sort == Skylable_AccessSx::SORT_BY_NAME_DESC ? Skylable_AccessSx::SORT_BY_NAME_ASC : Skylable_AccessSx::SORT_BY_NAME_DESC ); ?>" class="sort-name"><?php echo $this->translate('Name'); ?><span class="icon-sort<?php echo ($this->sort == Skylable_AccessSx::SORT_BY_NAME_DESC ? ' down' : ($this->sort == Skylable_AccessSx::SORT_BY_NAME_ASC ? ' up' : '' ) ); ?>"></span></a>
            </span><span class="size"><a href="?sort=<?php echo ($this->sort == Skylable_AccessSx::SORT_BY_SIZE_DESC ? Skylable_AccessSx::SORT_BY_SIZE_ASC : Skylable_AccessSx::SORT_BY_SIZE_DESC ); ?>" class="sort-size"><?php echo $this->translate('Size'); ?><span class="icon-sort<?php echo ($this->sort == Skylable_AccessSx::SORT_BY_SIZE_DESC ? ' down' : ($this->sort == Skylable_AccessSx::SORT_BY_SIZE_ASC ? ' up' : '' ) ); ?>"></span></a>
            </span><span class="date"><a href="?sort=<?php echo ($this->sort == Skylable_AccessSx::SORT_BY_DATE_DESC ? Skylable_AccessSx::SORT_BY_DATE_ASC : Skylable_AccessSx::SORT_BY_DATE_DESC ); ?>" class="sort-date"><?php echo $this->translate('Date'); ?><span class="icon-sort<?php echo ($this->sort == Skylable_AccessSx::SORT_BY_DATE_DESC ? ' down' : ($this->sort == Skylable_AccessSx::SORT_BY_DATE_ASC ? ' up' : '' ) ); ?>"></span></a></span>
		</p>
	</div>
</div>	
<div class="wrap">
	<div id="main-file-list">
		<?php echo $this->render('directory_listing.phtml'); ?>
	</div>
	<?php echo $this->render('footer.phtml'); ?>
</div>
<?php
if (isset($this->show_welcome_window)) {
	if ($this->show_welcome_window) {
		echo $this->render('index/welcome.phtml');
	}
}
