<?php 
    // In demo mode, pre-fill the form
    $user_login = '';
    $user_password = '';
    $demo_mode = FALSE;
    if (defined('SXWEB_DEMO_MODE')) {
        if (SXWEB_DEMO_MODE) {
            $demo_mode = TRUE;
            if (defined('SXWEB_DEMO_LOGIN')) {
                $user_login = SXWEB_DEMO_LOGIN;
            }
            if (defined('SXWEB_DEMO_PASSWORD')) {
                $user_password = SXWEB_DEMO_PASSWORD;
            }
        }
    }
    $this->headLink()->appendStylesheet($this->serverUrl() . '/layouts/skylable/css/pagedialog.css');
?>
<div class="dialog-box">
    <div class="dialog-box-logo">
        <span class="dialog-box-logo-icon ir"></span><h1><?php echo $this->translate('Login'); ?></h1>
    </div>
    <div class="dialog-box-body">
        <?php echo $this->form('', $this->form->getAttribs()); ?>
        <input type="text" value="<?php echo $this->escape($user_login); ?>" name="frm_login" placeholder="<?php echo $this->translate('Username'); ?>" />
        <input type="password" value="<?php echo $this->escape($user_password); ?>" name="frm_password" placeholder="<?php echo $this->translate('Password'); ?>" />
        <label for="confirm"><input type="checkbox" name="frm_remember_me" value="yes" id="confirm" /><?php echo $this->translate('Remember me'); ?></label>
       
        <div class="dialog-box-buttons">
            <?php if (My_Utils::passwordRecoveryIsAllowed()): ?>
                <a href="<?php echo $this->url(array( 'controller' => 'index', 'action' => 'resetpassword' ), 'recover', TRUE, TRUE );  ?>"><?php echo $this->translate('Forgot Your Password?'); ?></a>
            <?php endif; ?>
            <input type="submit" value="<?php echo $this->translate('Sign in'); ?>" />
        </div>
        </form>
    </div>

    <?php

    if ($this->form->hasErrors()):
        ?>
        <div class="failure notification-fix"><span class="inf" ><span class="icon-failure ir"></span></span>
            <?php echo $this->form->renderErrors(); ?>
        </div>
    <?php

    endif;

    echo $this->render('index/messages.phtml');
    ?>
</div>



