<?php 
    // In demo mode, pre-fill the form
    $user_login = '';
    $user_password = '';
    $demo_mode = FALSE;
    if (defined('SXWEB_DEMO_MODE')) {
        if (SXWEB_DEMO_MODE) {
            $demo_mode = TRUE;
            if (defined('SXWEB_DEMO_LOGIN')) {
                $user_login = SXWEB_DEMO_LOGIN;
            }
            if (defined('SXWEB_DEMO_PASSWORD')) {
                $user_password = SXWEB_DEMO_PASSWORD;
            }
        }
    }
?>
<div class="login-box">
    <div class="login-logo">
        <span class="icon-logo ir"></span><h1>Login</h1>
    </div>

    <div class="login-form">
    <?php echo $this->form('', $this->form->getAttribs()); ?>
        <input type="text" value="<?php echo $this->escape($user_login); ?>" name="frm_login" placeholder="Login" />
        <input type="password" value="<?php echo $this->escape($user_password); ?>" name="frm_password" placeholder="Password" />
        <label for="confirm"><input type="checkbox" name="frm_remember_me" value="yes" id="confirm" />Remember me</label>
        <input type="submit" value="Sign in" />
    </form>
    </div>

    <div class="login-utils">
        <?php if (My_Utils::passwordRecoveryIsAllowed()): ?>
        <a href="<?php echo $this->url(array( 'controller' => 'index', 'action' => 'resetpassword' ), 'recover', TRUE, TRUE );  ?>">Forgot Your Password?</a>
        <?php endif; ?>
    </div>
<?php
    
    if ($this->form->hasErrors()):
?>
    <div class="failure notification-fix"><span class="inf" ><span class="icon-failure ir"></span></span>
    <?php echo $this->form->renderErrors(); ?>
    </div>
<?php
        
    endif;

    echo $this->render('index/messages.phtml');
?>
</div>
