<div class="login-box register">
	<div class="login-logo">
		<span class="icon-logo ir"></span><h1>Change password</h1>
	</div>
<style>
.change_password {
height:170px!important;
}
.change_password label {
float:left;
width:100px;
}
.change_password  input[type=password] {
	width:100%;
}
</style>
<div class="login-form change_password">	
	<form method="post" action="">
		<p>
			<input type="password" value="" name="passwd" placeholder="New password" />
			<input type="password" value="" name="passwd2" placeholder="Confirm password"/>
		</p>
		<p>	
			<input type ="submit" value="Change!" />
		</p>
	</form>
</div>
<?php

    if (isset($this->notifications)) {
        foreach($this->notifications as $notify_msg) { ?>
            <div class="info notification-fix"><span class="inf" ><span class="icon-failure ir"></span><?php echo $this->escape($notify_msg); ?></span></div>
        <?php
        }
    }

    if (isset($this->errors)) {
        foreach($this->errors as $err_msg) { ?>
            <div class="failure notification-fix"><span class="inf" ><span class="icon-failure ir"></span><?php echo $this->escape($err_msg); ?></span></div>
        <?php
        }
    }
?>
</div>
