<?php $this->headLink()->appendStylesheet($this->serverUrl() . '/layouts/skylable/css/pagedialog.css'); ?>
<div class="dialog-box">
	<div class="dialog-box-logo">
		<a href="<?php echo $this->escape(SKYLABLE_SITE_URL); ?>" onclick="window.open(this.href); return false;"><span class="dialog-box-logo-icon ir"></span></a><h1><?php echo $this->translate('Change password'); ?></h1>
	</div>
	<div class="dialog-box-body">
		<form action="" method="post">
			<input type="password" value="" name="passwd" placeholder="<?php echo $this->translate('New Password'); ?>" />
			<input type="password" value="" name="passwd2" placeholder="<?php echo $this->translate('Confirm Password'); ?>"/>

			<div class="dialog-box-buttons">
                <a href="<?php echo $this->escape($this->serverUrl()); ?>"><?php echo $this->translate('Cancel'); ?></a>
                <input type="submit" value="<?php echo $this->translate('Change!'); ?>" />
			</div>
		</form>
	</div>
	<div class="dialog-box-utils">
		<!-- <a href="<?php echo $this->escape($this->serverUrl()); ?>"><?php echo $this->translate('Sign in'); ?></a> -->
	</div>

	<?php

	if (isset($this->notifications)) {
		foreach($this->notifications as $notify_msg) { ?>
			<div class="info notification-fix"><span class="inf" ><span class="icon-failure ir"></span><?php echo $this->escape($notify_msg); ?></span></div>
			<?php
		}
	}

	if (isset($this->errors)) {
		foreach($this->errors as $err_msg) { ?>
			<div class="failure notification-fix"><span class="inf" ><span class="icon-failure ir"></span><?php echo $this->escape($err_msg); ?></span></div>
			<?php
		}
	}

	echo $this->render('index/messages.phtml');
	?>
	<div class="dialog-box-fixed-footer"><?php printf($this->translate('Powered by %s.'), '<a href="' . $this->escape(SKYLABLE_SITE_URL) . '" onclick="window.open(this.href); return false;">'  .  $this->escape(SKYLABLE_LABEL) . '</a>'); ?></div>
</div>