<?php $this->headLink()->appendStylesheet($this->serverUrl() . '/layouts/skylable/css/pagedialog.css'); ?>
<div class="dialog-box">
    <div class="dialog-box-logo">
        <a href="<?php echo $this->escape(SKYLABLE_SITE_URL); ?>" onclick="window.open(this.href); return false;"><span class="dialog-box-logo-icon ir"></span></a><h1><?php echo $this->translate('Reset password'); ?></h1>
    </div>
    <div class="dialog-box-body">
        <p><?php echo $this->translate('Enter your email. You will receive a link to follow to reset your password.'); ?></p>
        
        <form action="<?php echo $this->escape($this->serverUrl('/reset/password')); ?>" method="post">
        <input type="email" name="email" value="" placeholder="<?php echo $this->translate('Email address'); ?>" />

        <div class="dialog-box-buttons">
            <a href="<?php echo $this->escape($this->serverUrl()); ?>"><?php echo $this->translate('Cancel'); ?></a>
            <input type="submit" value="<?php echo $this->translate('Reset password'); ?>" />
        </div>
        </form>
    </div>
    <div class="dialog-box-utils">
    
    </div>

    <?php

    if (isset($this->notifications)) {
        foreach($this->notifications as $notify_msg) { ?>
            <div class="info notification-fix"><span class="inf" ><span class="icon-failure ir"></span><?php echo $this->escape($notify_msg); ?></span></div>
            <?php
        }
    }

    if (isset($this->errors)) {
        foreach($this->errors as $err_msg) { ?>
            <div class="failure notification-fix"><span class="inf" ><span class="icon-failure ir"></span><?php echo $this->escape($err_msg); ?></span></div>
            <?php
        }
    }

    echo $this->render('index/messages.phtml');
    ?>
    <div class="dialog-box-fixed-footer"><?php printf($this->translate('Powered by %s.'), '<a href="' . $this->escape(SKYLABLE_SITE_URL) . '" onclick="window.open(this.href); return false;">'  .  $this->escape(SKYLABLE_LABEL) . '</a>'); ?></div>
</div>
