<div class="login-box register">
<div class="login-logo">
	<span class="icon-logo ir"></span><h1><?php echo $this->translate('Reset password'); ?></h1>
</div>
    
<div class="login-form" style="height:150px;">
	<p style="padding-bottom:10px;float:left;" ><?php echo $this->translate('Enter your email. You will receive a link to reset your password.'); ?></p>
	<form action="/reset/password" method="post" >
		<input type="email" name="email" value="" style="width:95%" placeholder="<?php echo $this->translate('Email address'); ?>" /> 
		<input type="submit" value="Reset" />
	</form>
</div>
    <?php

        if (isset($this->notifications)) {
            foreach($this->notifications as $notify_msg) { ?>
                <div class="info notification-fix"><span class="inf" ><span class="icon-failure ir"></span><?php echo $this->escape($notify_msg); ?></span></div>
            <?php
            }
        }
    
        if (isset($this->errors)) {
            foreach($this->errors as $err_msg) { ?>
                <div class="failure notification-fix"><span class="inf" ><span class="icon-failure ir"></span><?php echo $this->escape($err_msg); ?></span></div>
            <?php
            }
        }
    ?>
    
</div>