<hr><?php if (APPLICATION_ENV === 'development') echo '<p>SITE IS RUNNING IN DEVELOPMENT MODE</p>'; ?>
<?php if ($this->demoMode()) echo '<p>THIS IS A DEMO, MANY FUNCTIONALITIES ARE PARTIALLY OR COMPLETELY DISABLED TO PREVENT ABUSE.</p>'; ?>
<p class="copyright">Copyright &copy; 2012-2015 Skylable Ltd. All Rights Reserved. Version: <?php echo SXWEB_VERSION; ?></p>
<div class="footer-logo ir"></div>
