<?php $the_url_to_follow = $this->url.'/reset/password/'.$this->hash; ?>
<h1><?php echo $this->translate('SXWeb - Change your password'); ?></h1>
<p><?php printf($this->translate('To change your password please follow this link: %s'), '<a href="' . $this->escape($the_url_to_follow) . '">' . $this->escape($the_url_to_follow) . '</a>'); ?></p>
<br />
<p><?php echo $this->translate('This link is valid for 24 hours.'); ?></p>
<hr />
<p><small><?php echo $this->translate('This message was generated automatically.'); ?></small></p>