<?php

/*
 * Contains the action menu into the sidebar.
 */

?>
	<div class="sidebar-tools">
	<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
            <a href="/settings" title="<?php echo $this->translate('Manage your account');?>"><span class="icon-settings ir"></span><span><?php echo $this->translate('My Account'); ?></span></a>
			<a href="/logout"><span class="icon-logout ir"></span><span><?php echo $this->translate('Logout'); ?></span></a>
	<?php else: ?>		
			<a href="/login"><span class="icon-login ir"></span><span><?php echo $this->translate('Login'); ?></span></a>
	<?php endif; ?>		
		<hr />
		<a href="<?php echo $this->escape(Zend_Registry::get('skylable')->get('tech_support_url')); ?>" onclick="window.open(this.href); return false;"><span class="icon-support ir"></span><span><?php echo $this->translate('Tech Support'); ?></span></a>
	</div>
