<?php

/*
 * Contains the action menu into the sidebar.
 */

$cookie_auth_key = Zend_Registry::get('skylable')->get('cookie_auth_key');
$authenticate_by_cookie = isset($cookie_auth_key) && isset($_COOKIE['sxweb_login']);
?>
	<div class="sidebar-tools">
	<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
            <a href="<?php echo $this->ServerUrl(); ?>/settings" title="<?php echo $this->translate('Manage your account');?>"><span class="icon-settings ir"></span><span><?php echo $this->translate('Settings'); ?></span></a>
                        <?php if(!$authenticate_by_cookie): ?>
			<a href="<?php echo $this->ServerUrl(); ?>/logout"><span class="icon-logout ir"></span><span><?php echo $this->translate('Logout'); ?></span></a>
                        <?php endif; ?>
	<?php else: ?>		
			<a href="<?php echo $this->ServerUrl(); ?>/login"><span class="icon-login ir"></span><span><?php echo $this->translate('Login'); ?></span></a>
	<?php endif; ?>		
		<hr />
		<a href="<?php echo $this->escape(Zend_Registry::get('skylable')->get('tech_support_url')); ?>" onclick="window.open(this.href); return false;"><span class="icon-support ir"></span><span><?php echo $this->translate('Tech Support'); ?></span></a>
	</div>
