<?php
/*
    The contents of this file are subject to the Common Public Attribution License
    Version 1.0 (the "License"); you may not use this file except in compliance with
    the License. You may obtain a copy of the License at
    http://opensource.org/licenses/cpal_1.0. The License is based on the Mozilla
    Public License Version 1.1 but Sections 14 and 15 have been added to cover use
    of software over a computer network and provide for limited attribution for the
    Original Developer. In addition, Exhibit A has been modified to be consistent with
    Exhibit B.
    
    Software distributed under the License is distributed on an "AS IS" basis, WITHOUT
    WARRANTY OF ANY KIND, either express or implied. See the License for the
    specific language governing rights and limitations under the License.
    
    The Original Code is the SXWeb project.
    
    The Original Developer is the Initial Developer.
    
    The Initial Developer of the Original Code is Skylable Ltd (info-copyright@skylable.com). 
    All portions of the code written by Initial Developer are Copyright (c) 2013 - 2015
    the Initial Developer. All Rights Reserved.

    Contributor(s):    

    Alternatively, the contents of this file may be used under the terms of the
    Skylable White-label Commercial License (the SWCL), in which case the provisions of
    the SWCL are applicable instead of those above.
    
    If you wish to allow use of your version of this file only under the terms of the
    SWCL and not to allow others to use your version of this file under the CPAL, indicate
    your decision by deleting the provisions above and replace them with the notice
    and other provisions required by the SWCL. If you do not delete the provisions
    above, a recipient may use your version of this file under either the CPAL or the
    SWCL.
*/

?>
<div class="jumbotron">
    <h1><?php echo $this->translate('Welcome!'); ?></h1>
    <p><?php echo $this->translate('You are about to configure your new Skylable SXWeb installation.'); ?></p>
</div>
<p><?php echo $this->translate('Before getting started you need these informations:'); ?></p>
<ul>
    <li><?php echo $this->translate('A MySQL database account, with user name, password, host and (eventually) port to access the DB server.'); ?></li>
    <li><?php echo $this->translate('The address of the SX Cluster you want to use.'); ?></li>
    <li><?php echo $this->translate('A SMTP host to use for sending email.'); ?></li>
</ul>
<p><?php echo $this->translate('This installer will help you to generate the file <code>skylable.ini</code> and save it to the proper place into your Skylable SXWeb installation.'); ?></p>
<p><?php echo $this->translate('Please read the file <code>docs/deploy.md</code> for complete deploy instructions.'); ?></p>
<?php if (defined('SXWEB_FAQ_URL')): ?>
    <p><?php printf($this->translate('You can find the SXWeb FAQ here: %s'), '<a href="' . $this->escape(SXWEB_FAQ_URL) .'" onclick="window.open(this.href); return false;">' . $this->escape(SXWEB_FAQ_URL) .'</a>'); ?></p>
<?php endif; ?>
<?php if (isset($this->installer_not_writable)): ?>
<div class="alert alert-danger" role="alert">
    <strong><?php echo $this->translate('Security Risk Alert!'); ?></strong> <?php printf($this->translate('The installer script <code>%s</code> seems not modifiable. At the end of the installation/upgrade process you should remove it or make it unreadable by the web server to avoid security risks.'), realpath(INSTALLER_SCRIPT_PATH)); ?>
</div>
<?php endif; ?>
<p><a class="btn btn-default" href="<?php echo $this->ServerUrl(); ?>/install.php?step=base"><?php echo $this->translate('Continue...'); ?></a></p>