<?php
/*
    The contents of this file are subject to the Common Public Attribution License
    Version 1.0 (the "License"); you may not use this file except in compliance with
    the License. You may obtain a copy of the License at
    http://opensource.org/licenses/cpal_1.0. The License is based on the Mozilla
    Public License Version 1.1 but Sections 14 and 15 have been added to cover use
    of software over a computer network and provide for limited attribution for the
    Original Developer. In addition, Exhibit A has been modified to be consistent with
    Exhibit B.
    
    Software distributed under the License is distributed on an "AS IS" basis, WITHOUT
    WARRANTY OF ANY KIND, either express or implied. See the License for the
    specific language governing rights and limitations under the License.
    
    The Original Code is the SXWeb project.
    
    The Original Developer is the Initial Developer.
    
    The Initial Developer of the Original Code is Skylable Ltd (info-copyright@skylable.com). 
    All portions of the code written by Initial Developer are Copyright (c) 2013 - 2015
    the Initial Developer. All Rights Reserved.

    Contributor(s):    

    Alternatively, the contents of this file may be used under the terms of the
    Skylable White-label Commercial License (the SWCL), in which case the provisions of
    the SWCL are applicable instead of those above.
    
    If you wish to allow use of your version of this file only under the terms of the
    SWCL and not to allow others to use your version of this file under the CPAL, indicate
    your decision by deleting the provisions above and replace them with the notice
    and other provisions required by the SWCL. If you do not delete the provisions
    above, a recipient may use your version of this file under either the CPAL or the
    SWCL.
*/
?>
<div class="page-header">
    <h1><?php echo $this->translate('Database Setup'); ?></h1>
</div>
<p><?php echo $this->translate('Setup the database connection.'); ?></p>
<?php
if (isset($this->errors)): ?>
    
    <div class="panel panel-danger">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->translate('There are errors!'); ?></h3>
        </div>
        <div class="panel-body">
<?php
            $map = array(
                'frm_db_name' => 'Database Name',
                'frm_db_host' => 'Database Host',
                'frm_db_port' => 'Database Port',
                'frm_db_user' => 'User Name',
                'frm_db_password' => 'Password'
            );

            echo '<p>',$this->translate('The following field(s) have errors, please correct them:'),'</p>',PHP_EOL;
            echo '<dl>';
            foreach($this->errors as $field => $err_msg) {

                echo '<dt>',$map[ $field ],'</dt>',PHP_EOL;
                foreach($err_msg as $m) {
                    echo '<dd>',$m,'</dd>',PHP_EOL;
                }

            }
            echo '</dl>'; 
?>
        </div>
    </div>
<?php

endif;
?>
<form method="post" class="form-horizontal" action="<?php echo $this->escape( $this->ServerUrl() . '/install.php?step=step2' )?>">
         <div class="form-group<?php if (isset($this->errors['frm_db_name'])) echo ' has-error'; ?>">
            <label for="frm_db_name" class="col-sm-2 control-label"><?php echo $this->translate('Database Name'); ?></label>
            <div class="col-sm-10">
                <input name="frm_db_name" class="form-control" id="frm_db_name" type="text" size="25" value="<?php echo $this->escape( $this->frm_db_name ); ?>" />
                <span class="help-block"><?php echo $this->translate('The name of the database you want SXWeb to run in.'); ?></span>
            </div>
        </div>
        <div class="form-group<?php if (isset($this->errors['frm_db_user'])) echo ' has-error'; ?>">
            <label for="frm_db_user" class="col-sm-2 control-label"><?php echo $this->translate('User name'); ?></label>
            <div class="col-sm-10">
                <input name="frm_db_user" class="form-control" id="frm_db_user" type="text" size="25" value="<?php echo $this->escape( $this->frm_db_user ); ?>" />
                <span class="help-block"><?php echo $this->translate('The MySQL user name.'); ?></span>
            </div>
        </div>
        <div class="form-group<?php if (isset($this->errors['frm_db_password'])) echo ' has-error'; ?>">
            <label for="frm_db_password" class="col-sm-2 control-label"><?php echo $this->translate('Password'); ?></label>
            <div class="col-sm-10">
            <input class="form-control" name="frm_db_password" id="frm_db_password" type="password" size="25" value="" />
            <span class="help-block"><?php echo $this->translate('The MySQL password.'); ?></span>
                </div>
        </div>
        <div class="form-group<?php if (isset($this->errors['frm_db_host'])) echo ' has-error'; ?>">
            <label for="frm_db_host" class="col-sm-2 control-label"><?php echo $this->translate('Database Host'); ?></label>
            <div class="col-sm-10">
            <input class="form-control" name="frm_db_host" id="frm_db_host" type="text" size="25" value="<?php echo $this->escape( $this->frm_db_host ); ?>" />
            <span class="help-block"><?php echo $this->translate('The MySQL Server hostname, usually <code>localhost</code>.'); ?></span>
                </div>
        </div>
        <div class="form-group<?php if (isset($this->errors['frm_db_port'])) echo ' has-error'; ?>">
            <label for="frm_db_port" class="col-sm-2 control-label"><?php echo $this->translate('Database Port'); ?></label>
            <div class="col-sm-10">
            <input class="form-control" name="frm_db_port" id="frm_db_port" type="text" size="25" value="<?php echo $this->escape( $this->frm_db_port ); ?>" />
            <span class="help-block"><?php echo $this->translate('The MySQL Server port. Leave blank to use the default <code>3306</code>.'); ?></span>
                </div>
        </div>

    <button type="submit" class="btn btn-default"><?php echo $this->translate('Submit') ?></button>
    
</form>
