<?php
/*
    The contents of this file are subject to the Common Public Attribution License
    Version 1.0 (the "License"); you may not use this file except in compliance with
    the License. You may obtain a copy of the License at
    http://opensource.org/licenses/cpal_1.0. The License is based on the Mozilla
    Public License Version 1.1 but Sections 14 and 15 have been added to cover use
    of software over a computer network and provide for limited attribution for the
    Original Developer. In addition, Exhibit A has been modified to be consistent with
    Exhibit B.
    
    Software distributed under the License is distributed on an "AS IS" basis, WITHOUT
    WARRANTY OF ANY KIND, either express or implied. See the License for the
    specific language governing rights and limitations under the License.
    
    The Original Code is the SXWeb project.
    
    The Original Developer is the Initial Developer.
    
    The Initial Developer of the Original Code is Skylable Ltd (info-copyright@skylable.com). 
    All portions of the code written by Initial Developer are Copyright (c) 2013 - 2015
    the Initial Developer. All Rights Reserved.

    Contributor(s):    

    Alternatively, the contents of this file may be used under the terms of the
    Skylable White-label Commercial License (the SWCL), in which case the provisions of
    the SWCL are applicable instead of those above.
    
    If you wish to allow use of your version of this file only under the terms of the
    SWCL and not to allow others to use your version of this file under the CPAL, indicate
    your decision by deleting the provisions above and replace them with the notice
    and other provisions required by the SWCL. If you do not delete the provisions
    above, a recipient may use your version of this file under either the CPAL or the
    SWCL.
*/
?>
<div class="page-header">
    <h1><?php echo $this->translate('Mail Transport Setup'); ?></h1>
</div>
<p><?php echo $this->translate('Setup the mail transport.'); ?></p>
<?php
if (isset($this->errors)): ?>
    
    <div class="panel panel-danger">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->translate('There are errors!'); ?></h3>
        </div>
        <div class="panel-body">
<?php
            $map = array(
                'frm_mail_type' => $this->translate('Transport Type'),
                'frm_mail_smtp_host' => $this->translate('SMTP Host'),
                'frm_mail_sender_host' => $this->translate('Sender Host Name'),
                'frm_mail_ssl' => $this->translate('Use SSL'),
                'frm_mail_port' => $this->translate('SMTP port'),
                
                'frm_mail_auth' => $this->translate('Auth Type'),
                'frm_mail_username' => $this->translate('User Name'),
                'frm_mail_password' => $this->translate('Password'),
                
                'frm_default_from_mail' => $this->translate('&quot;From&quot; Address'),
                'frm_default_from_name' => $this->translate('&quot;From&quot; Name'),

                'frm_default_replyto_mail' => $this->translate('&quot;Reply To&quot; Address'),
                'frm_default_replyto_name' => $this->translate('&quot;Reply To&quot; Name')

            );

            echo '<p>',$this->translate('The following field(s) have errors, please correct them:'),'</p>',PHP_EOL;
            echo '<dl>';
            foreach($this->errors as $field => $err_msg) {

                echo '<dt>',$map[ $field ],'</dt>',PHP_EOL;
                foreach($err_msg as $m) {
                    echo '<dd>',$m,'</dd>',PHP_EOL;
                }

            }
            echo '</dl>'; 
?>
        </div>
    </div>
<?php

endif;
?>
<form method="post" class="form-horizontal" action="<?php echo $this->escape( $this->ServerUrl() . '/install.php?step=step4' )?>">
    <fieldset>
        <legend><?php echo $this->translate('Base settings'); ?></legend>
         <div class="form-group<?php if (isset($this->errors['frm_mail_type'])) echo ' has-error'; ?>">
            <label for="frm_mail_type" class="col-sm-2 control-label"><?php echo $this->translate('Transport Type'); ?></label>
            <div class="col-sm-10">
                <?php echo $this->formSelect('frm_mail_type', $this->frm_mail_type, array('class' => 'form-control'), array( 'smtp' => 'SMTP', 'sendmail' => 'Sendmail' ) );  ?>
                <span class="help-block"><?php echo $this->translate('The transport type to use.'); ?></span>
            </div>
        </div>

        <div class="form-group<?php if (isset($this->errors['frm_mail_smtp_host'])) echo ' has-error'; ?>">
            <label for="frm_mail_smtp_host" class="col-sm-2 control-label"><?php echo $this->translate('SMTP Host'); ?></label>
            <div class="col-sm-10">
                <input class="form-control" name="frm_mail_smtp_host" id="frm_mail_smtp_host" type="text" size="25" value="<?php echo $this->escape( $this->frm_mail_smtp_host ); ?>" />
                <span class="help-block"><?php echo $this->translate('The SMTP host which relays or sends your emails. Use <code>localhost</code> for a &quot;Sendmail&quot; transport.'); ?></span>
            </div>
        </div>

        <div class="form-group<?php if (isset($this->errors['frm_mail_sender_host'])) echo ' has-error'; ?>">
            <label for="frm_mail_sender_host" class="col-sm-2 control-label"><?php echo $this->translate('Sender Host Name'); ?></label>
            <div class="col-sm-10">
                <input class="form-control" name="frm_mail_sender_host" id="frm_mail_sender_host" type="text" size="25" value="<?php echo $this->escape( $this->frm_mail_sender_host ); ?>" />
                <span class="help-block"><?php echo $this->translate('To avoid been marked as a spammer, use this host when connecting to the SMTP host. Don&apos;t use <code>localhost</code> if you send emails using SMTP. You can safely leave this field blank.'); ?></span>
            </div>
        </div>

        <div class="form-group<?php if (isset($this->errors['frm_mail_ssl'])) echo ' has-error'; ?>">
            <label for="frm_mail_ssl" class="col-sm-2 control-label"><?php echo $this->translate('Use SSL'); ?></label>
            <div class="col-sm-10">
                <?php echo $this->formSelect('frm_mail_ssl', $this->frm_mail_ssl, array('class' => 'form-control'), array( '' => $this->translate('No'), 'tls' => 'TLS', 'ssl' => 'SSL' ) );  ?>
                <span class="help-block"><?php echo $this->translate('SSL protocol to use.'); ?></span>
            </div>
        </div>

        <div class="form-group<?php if (isset($this->errors['frm_mail_port'])) echo ' has-error'; ?>">
            <label for="frm_mail_port" class="col-sm-2 control-label"><?php echo $this->translate('SMTP port'); ?></label>
            <div class="col-sm-10">
                <input class="form-control" name="frm_mail_port" id="frm_mail_port" type="text" size="25" value="<?php echo $this->escape( $this->frm_mail_port ); ?>" />
                <span class="help-block"><?php echo $this->translate('SMTP server port. Leave blank for default (25 for TLS or 465 for SSL).'); ?></span>
            </div>
        </div>
        
    </fieldset>
    
    <fieldset>
        <legend><?php echo $this->translate('SMTP Auth parameters'); ?></legend>

        <div class="form-group<?php if (isset($this->errors['frm_mail_auth'])) echo ' has-error'; ?>">
            <label for="frm_mail_auth" class="col-sm-2 control-label"><?php echo $this->translate('Auth Type'); ?></label>
            <div class="col-sm-10">
                <?php echo $this->formSelect('frm_mail_auth', $this->frm_mail_auth, array('class' => 'form-control'), array( 'none' => $this->translate('None'), 'plain' => 'PLAIN', 'login' => 'LOGIN', 'crammd5' => 'CRAM-MD5' ) );  ?>
                <span class="help-block"><?php echo $this->translate('The auth type to use.'); ?></span>
            </div>
        </div>
    
        <div class="form-group<?php if (isset($this->errors['frm_mail_user'])) echo ' has-error'; ?>">
            <label for="frm_mail_username" class="col-sm-2 control-label"><?php echo $this->translate('User name'); ?></label>
            <div class="col-sm-10">
                <input name="frm_mail_username" class="form-control" id="frm_mail_username" type="text" size="25" value="<?php echo $this->escape( $this->frm_mail_username ); ?>" />
                <span class="help-block"><?php echo $this->translate('The SMTP Auth user name.'); ?></span>
            </div>
        </div>
        <div class="form-group<?php if (isset($this->errors['frm_mail_password'])) echo ' has-error'; ?>">
            <label for="frm_mail_password" class="col-sm-2 control-label"><?php echo $this->translate('Password'); ?></label>
            <div class="col-sm-10">
            <input class="form-control" name="frm_mail_password" id="frm_mail_password" type="password" size="25" value="<?php echo $this->escape( $this->frm_mail_password ); ?>" />
            <span class="help-block"><?php echo $this->translate('The SMTP password.'); ?></span>
                </div>
        </div>
        </fieldset>
     

    <fieldset>
        <legend><?php echo $this->translate('Default Addresses'); ?></legend>
    <p><?php echo $this->translate('The only mandatory field is the &quot;From Address&quot;'); ?></p>
    <div class="form-group<?php if (isset($this->errors['frm_default_from_mail'])) echo ' has-error'; ?>">
        <label for="frm_default_from_mail" class="col-sm-2 control-label"><?php echo $this->translate('&quot;From&quot; Address'); ?></label>
        <div class="col-sm-10">
            <input class="form-control" name="frm_default_from_mail" id="frm_default_from_mail" type="text" size="25" value="<?php echo $this->escape( $this->frm_default_from_mail ); ?>" />
            <span class="help-block"><?php echo $this->translate('The default &quot;From&quot; address.'); ?></span>
        </div>
    </div>
    <div class="form-group<?php if (isset($this->errors['frm_default_from_name'])) echo ' has-error'; ?>">
        <label for="frm_default_from_name" class="col-sm-2 control-label"><?php echo $this->translate('&quot;From&quot; Name'); ?></label>
        <div class="col-sm-10">
            <input class="form-control" name="frm_default_from_name" id="frm_default_from_name" type="text" size="25" value="<?php echo $this->escape( $this->frm_default_from_name ); ?>" />
            <span class="help-block"><?php echo $this->translate('The default &quot;From&quot; name.'); ?></span>
        </div>
    </div>
    <div class="form-group<?php if (isset($this->errors['frm_default_to_mail'])) echo ' has-error'; ?>">
        <label for="frm_default_replyto_mail" class="col-sm-2 control-label"><?php echo $this->translate('&quot;Reply To&quot; Address'); ?></label>
        <div class="col-sm-10">
            <input class="form-control" name="frm_default_replyto_mail" id="frm_default_replyto_mail" type="text" size="25" value="<?php echo $this->escape( $this->frm_default_replyto_mail ); ?>" />
            <span class="help-block"><?php echo $this->translate('The default &quot;Reply To&quot; address.'); ?></span>
        </div>
    </div>
    <div class="form-group<?php if (isset($this->errors['frm_default_replyto_name'])) echo ' has-error'; ?>">
        <label for="frm_default_replyto_name" class="col-sm-2 control-label"><?php echo $this->translate('&quot;Reply To&quot; Name'); ?></label>
        <div class="col-sm-10">
            <input class="form-control" name="frm_default_replyto_name" id="frm_default_replyto_name" type="text" size="25" value="<?php echo $this->escape( $this->frm_default_replyto_name ); ?>" />
            <span class="help-block"><?php echo $this->translate('The default &quot;Reply To&quot; name.'); ?></span>
        </div>
    </div>
    </fieldset>

    <p><button type="submit" class="btn btn-primary"><?php echo $this->translate('Submit!') ?></button> <a class="btn btn-default" href="<?php echo $this->ServerUrl(); ?>/install.php?step=step3"><?php echo $this->translate('Go to previous step...');?></a></p>
    
</form>
