<?php
/*
    The contents of this file are subject to the Common Public Attribution License
    Version 1.0 (the "License"); you may not use this file except in compliance with
    the License. You may obtain a copy of the License at
    http://opensource.org/licenses/cpal_1.0. The License is based on the Mozilla
    Public License Version 1.1 but Sections 14 and 15 have been added to cover use
    of software over a computer network and provide for limited attribution for the
    Original Developer. In addition, Exhibit A has been modified to be consistent with
    Exhibit B.
    
    Software distributed under the License is distributed on an "AS IS" basis, WITHOUT
    WARRANTY OF ANY KIND, either express or implied. See the License for the
    specific language governing rights and limitations under the License.
    
    The Original Code is the SXWeb project.
    
    The Original Developer is the Initial Developer.
    
    The Initial Developer of the Original Code is Skylable Ltd (info-copyright@skylable.com). 
    All portions of the code written by Initial Developer are Copyright (c) 2013 - 2015
    the Initial Developer. All Rights Reserved.

    Contributor(s):    

    Alternatively, the contents of this file may be used under the terms of the
    Skylable White-label Commercial License (the SWCL), in which case the provisions of
    the SWCL are applicable instead of those above.
    
    If you wish to allow use of your version of this file only under the terms of the
    SWCL and not to allow others to use your version of this file under the CPAL, indicate
    your decision by deleting the provisions above and replace them with the notice
    and other provisions required by the SWCL. If you do not delete the provisions
    above, a recipient may use your version of this file under either the CPAL or the
    SWCL.
*/
?>
<div class="page-header">
    <h1><?php echo $this->title; ?></h1>
</div>
<?php if (isset($this->installer_not_writable)): ?>
    <div class="alert alert-danger" role="alert">
        <strong><?php echo $this->translate('Security Risk Alert!'); ?></strong> <?php printf($this->translate('The installer script <code>%s</code> is not modifiable. You should remove it or make it unreadable by the web server to avoid security risks.'), realpath(INSTALLER_SCRIPT_PATH)); ?>
    </div>
<?php else: ?>
    <div class="alert alert-info" role="alert">
        <strong><?php echo $this->translate('Important!'); ?></strong> <?php printf($this->translate('The installer script <code>%s</code> has been renamed to <code>%s</code> for security reasons.'), INSTALLER_SCRIPT_PATH, $this->new_install_script_name); ?> 
    </div>
<?php endif; ?>
<?php
    if ($this->write_success):
?>
        <div class="alert alert-success"><?php echo $this->translate('<strong>Success!</strong> You have successfully configured your Skylable SXWeb installation!'); ?></div>
        <p><?php printf($this->translate('You can find the <code>skylable.ini</code> file here: <code>%s</code>.'), $this->skylable_ini_path); ?></p>
        <p><a href="<?php echo $this->ServerUrl(); ?>" class="btn btn-default"><?php echo $this->translate('Start using it!'); ?></a></p>
<?php
    else:
?><div class="alert alert-warning"><?php printf($this->translate('<strong>Ops!</strong> There is a problem: %s'), $this->reason); ?></div>
        <p><?php echo $this->translate('Failed to write the configuration file, but you can copy and paste the code below.'); ?></p>
        <p><?php printf($this->translate('You must put the <code>skylable.ini</code> file here: <code>%s</code>.'), $this->skylable_ini_path); ?></p>
        <textarea class="form-control" id="skylable_ini_text" rows="15" readonly><?php echo $this->escape( $this->skylable_ini ); ?></textarea>
        <script type="text/javascript"> $(document).ready(function(){ $('#skylable_ini_text').select();  }); </script>
        <p><a href="<?php echo $this->ServerUrl(); ?>" class="btn btn-default"><?php echo $this->translate('OK, I created the file manually!'); ?></a></p>
    <?php
    endif;

