<?php
/*
    The contents of this file are subject to the Common Public Attribution License
    Version 1.0 (the "License"); you may not use this file except in compliance with
    the License. You may obtain a copy of the License at
    http://opensource.org/licenses/cpal_1.0. The License is based on the Mozilla
    Public License Version 1.1 but Sections 14 and 15 have been added to cover use
    of software over a computer network and provide for limited attribution for the
    Original Developer. In addition, Exhibit A has been modified to be consistent with
    Exhibit B.
    
    Software distributed under the License is distributed on an "AS IS" basis, WITHOUT
    WARRANTY OF ANY KIND, either express or implied. See the License for the
    specific language governing rights and limitations under the License.
    
    The Original Code is the SXWeb project.
    
    The Original Developer is the Initial Developer.
    
    The Initial Developer of the Original Code is Skylable Ltd (info-copyright@skylable.com). 
    All portions of the code written by Initial Developer are Copyright (c) 2013 - 2015
    the Initial Developer. All Rights Reserved.

    Contributor(s):    

    Alternatively, the contents of this file may be used under the terms of the
    Skylable White-label Commercial License (the SWCL), in which case the provisions of
    the SWCL are applicable instead of those above.
    
    If you wish to allow use of your version of this file only under the terms of the
    SWCL and not to allow others to use your version of this file under the CPAL, indicate
    your decision by deleting the provisions above and replace them with the notice
    and other provisions required by the SWCL. If you do not delete the provisions
    above, a recipient may use your version of this file under either the CPAL or the
    SWCL.
*/

$this->headTitle($this->translate('Requirements'));
?>
<div class="page-header">
<h1><?php echo $this->translate('Requirements'); ?></h1>
    </div>
<p><?php echo $this->translate('These are the basic requirements to run Skylable SXWeb.'); ?></p>

<div class="page-header">
  <h2><?php echo $this->translate('PHP'); ?></h2>
</div>
<table class="table">
    <thead>
    <tr><th><?php echo $this->translate('Component'); ?></th><th><?php echo $this->translate('Required'); ?></th><th><?php echo $this->translate('Status'); ?></th></tr>
    </thead>
    <tbody>
    <?php
        foreach($this->php_components as $c) {
            echo '<tr><td>',$c[0],'</td><td>',$c[1],'</td><td>',$c[2],'</td></tr>',PHP_EOL; 
        }
    ?>
    </tbody>
</table>

<div class="page-header">
    <h2><?php echo $this->translate('PHP settings for uploads'); ?></h2>
</div>
<p><?php echo $this->translate('All these settings can be found into the <code>php.ini</code> configuration file.'); ?></p>
<table class="table">
    <thead>
    <tr><th><?php echo $this->translate('INI Setting'); ?></th><th><?php echo $this->translate('Value'); ?></th><th><?php echo $this->translate('Suggested'); ?></th></tr>
    </thead>
    <tbody>
    <?php
    foreach($this->php_ini_settings as $c) {
        echo '<tr><td>',$c[0],'</td><td>',$c[1],'</td><td>',$c[2],'</td></tr>',PHP_EOL;
    }
    ?>
    </tbody>
</table>
<p><?php printf($this->translate('With these settings, maximum upload file size is <strong>%d</strong> bytes'), $this->max_upload_filesize ); ?></p>

<div class="page-header">
    <h2><?php echo $this->translate('SX Commands'); ?></h2>
    </div>
<p><?php echo $this->translate('You must have installed all the Skylable SX commands to run SXWeb.'); ?></p>
<p><?php printf($this->translate('Commands are searched into these paths: <code>%s</code>'), $this->sx_commands_search_path); ?></p>
<table class="table">
    <thead>
    <tr><th><?php echo $this->translate('Command'); ?></th><th><?php echo $this->translate('Status'); ?></th></tr>
    </thead>
    <tbody>
    <?php
    foreach($this->sx_commands as $c) {
        echo '<tr><td>',$c[0],'</td><td>',$c[2],'</td></tr>',PHP_EOL;
    }
    ?>
    </tbody>
</table>
<?php 
if (isset($this->sx_commands_search_path_error)): ?>
<div class="alert alert-warning"><?php printf( $this->translate('<strong>Attention!</strong> %s'), $this->sx_commands_search_path_error); ?></div>
<?php
endif;
?>

<div class="page-header">
    <h2><?php echo $this->translate('SXWeb Data directory'); ?></h2>
</div>
<p><?php printf($this->translate('SXWeb uses the directory <code>%s</code> to store log files, session data, temporary uploads and user informations. This directory must be writable.'), APPLICATION_DATA_PATH); ?></p>
<p><?php echo $this->translate('<strong>Status</strong>: '), (isset($this->data_path_problem) ? $this->data_path_problem : $this->translate('OK!') ); ?> </p>
<?php if (isset($this->data_path_problem)): ?>
    <p><?php echo $this->translate('<em>Tip:</em> Verify that SELinux is not blocking the access to this directory.'); ?></p>
<?php endif; ?>
<?php if ($this->can_proceed): ?>
<p><a class="btn btn-default" href="<?php echo $this->ServerUrl(); ?>/install.php?step=step2"><?php echo $this->translate('Continue');?></a></p>
    <?php else: ?>
        <?php echo $this->translate('Please fulfill the basic requirements before continuing.'); ?></p>
        <p><a class="btn btn-default" href="<?php echo $this->ServerUrl(); ?>/install.php"><?php echo $this->translate('Retry');?></a></p>
    <?php endif; ?>
