<?php
/*
    The contents of this file are subject to the Common Public Attribution License
    Version 1.0 (the "License"); you may not use this file except in compliance with
    the License. You may obtain a copy of the License at
    http://opensource.org/licenses/cpal_1.0. The License is based on the Mozilla
    Public License Version 1.1 but Sections 14 and 15 have been added to cover use
    of software over a computer network and provide for limited attribution for the
    Original Developer. In addition, Exhibit A has been modified to be consistent with
    Exhibit B.
    
    Software distributed under the License is distributed on an "AS IS" basis, WITHOUT
    WARRANTY OF ANY KIND, either express or implied. See the License for the
    specific language governing rights and limitations under the License.
    
    The Original Code is the SXWeb project.
    
    The Original Developer is the Initial Developer.
    
    The Initial Developer of the Original Code is Skylable Ltd (info-copyright@skylable.com). 
    All portions of the code written by Initial Developer are Copyright (c) 2013 - 2015
    the Initial Developer. All Rights Reserved.

    Contributor(s):    

    Alternatively, the contents of this file may be used under the terms of the
    Skylable White-label Commercial License (the SWCL), in which case the provisions of
    the SWCL are applicable instead of those above.
    
    If you wish to allow use of your version of this file only under the terms of the
    SWCL and not to allow others to use your version of this file under the CPAL, indicate
    your decision by deleting the provisions above and replace them with the notice
    and other provisions required by the SWCL. If you do not delete the provisions
    above, a recipient may use your version of this file under either the CPAL or the
    SWCL.
*/
?>
<div class="page-header">
    <h1><?php echo $this->translate('SX Cluster configuration'); ?></h1>
</div>
<p><?php echo $this->translate('Setup your SX cluster connection.'); ?></p>
<?php
if (isset($this->errors)): ?>

    <div class="panel panel-danger">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->translate('There are errors!'); ?></h3>
        </div>
        <div class="panel-body">
            <?php
            $map = array(
                'frm_cluster' => $this->translate('SX Cluster Address'),
                'frm_cluster_ssl' => $this->translate('Use SSL'),
                'frm_cluster_port' => $this->translate('Cluster Port'),
                'frm_cluster_ip' => $this->translate('Cluster IP'),
                'frm_admin_key' => $this->translate('Admin Key'),
                'frm_allow_password_recovery' => $this->translate('Allow Password Recovery')
            );

            echo '<p>',$this->translate('The following field(s) have errors, please correct them:'),'</p>',PHP_EOL;
            echo '<dl>';
            foreach($this->errors as $field => $err_msg) {

                echo '<dt>',$map[ $field ],'</dt>',PHP_EOL;
                foreach($err_msg as $m) {
                    echo '<dd>',$m,'</dd>',PHP_EOL;
                }

            }
            echo '</dl>';
            ?>
        </div>
    </div>
<?php

endif;
?>
<form method="post" class="form-horizontal" action="<?php echo $this->escape( $this->ServerUrl() . '/install.php?step=step3' )?>">

    <fieldset>
        <legend><?php echo $this->translate('Basic settings'); ?></legend>
    
    <div class="form-group<?php if (isset($this->errors['frm_cluster'])) echo ' has-error'; ?>">
        <label for="frm_cluster" class="col-sm-2 control-label"><?php echo $this->translate('SX Cluster Address'); ?></label>
        <div class="col-sm-10">
            <input name="frm_cluster" class="form-control" id="frm_cluster" type="text" size="25" value="<?php echo $this->escape( $this->frm_cluster ); ?>" />
            <span class="help-block"><?php echo $this->translate('The address of the SX cluster you want to use. Format: <code>sx://somecluster.com</code>'); ?></span>
        </div>
    </div>

        <div class="form-group<?php if (isset($this->errors['frm_allow_password_recovery'])) echo ' has-error'; ?>">
            <label for="frm_allow_password_recovery" class="col-sm-2 control-label"><?php echo $this->translate('Allow Password Recovery'); ?></label>
            <div class="col-sm-10">
                <input type="checkbox" name="frm_allow_password_recovery" id="frm_allow_password_recovery" value="y" <?php echo ($this->frm_allow_password_recovery? 'checked="checked"' : '' ) ?> />
                <span class="help-block"><?php echo $this->translate('If password recovery is enabled, you <strong>must</strong> supply the Admin Key.'); ?></span>
            </div>
        </div>

        <div class="form-group<?php if (isset($this->errors['frm_admin_key'])) echo ' has-error'; ?>">
            <label for="frm_admin_key" class="col-sm-2 control-label"><?php echo $this->translate('Admin Key'); ?></label>
            <div class="col-sm-10">
                <input name="frm_admin_key" class="form-control" id="frm_admin_key" type="text" size="25" value="<?php echo $this->escape( $this->frm_admin_key ); ?>" />
                <span class="help-block"><?php echo $this->translate('The SX cluster admin key. Keep it safe.'); ?></span>
            </div>
        </div>
        </fieldset>
    
    <fieldset>
        <legend><?php echo $this->translate('Advanced settings'); ?></legend>
        <p><?php echo $this->translate('Leave these settings as is, unless you know what you are doing.'); ?></p>

        <div class="form-group<?php if (isset($this->errors['frm_cluster_ssl'])) echo ' has-error'; ?>">
            <label for="frm_cluster_ssl" class="col-sm-2 control-label"><?php echo $this->translate('Use SSL'); ?></label>
            <div class="col-sm-10">
                <input type="checkbox" name="frm_cluster_ssl" id="frm_cluster_ssl" value="y" <?php echo ($this->frm_cluster_ssl ? 'checked="checked"' : '' ) ?> />
                <span class="help-block"><?php echo $this->translate('Default is to use SSL.'); ?></span>
            </div>
        </div>

        <div class="form-group<?php if (isset($this->errors['frm_cluster_port'])) echo ' has-error'; ?>">
            <label for="frm_cluster_port" class="col-sm-2 control-label"><?php echo $this->translate('SX Cluster Port'); ?></label>
            <div class="col-sm-10">
                <input name="frm_cluster_port" class="form-control" id="frm_cluster_port" type="text" size="25" value="<?php echo $this->escape( $this->frm_cluster_port ); ?>" />
                <span class="help-block"><?php echo $this->translate('The port on which connect to the server.'); ?></span>
            </div>
        </div>


        <div class="form-group<?php if (isset($this->errors['frm_cluster_ip'])) echo ' has-error'; ?>">
            <label for="frm_cluster_ip" class="col-sm-2 control-label"><?php echo $this->translate('SX Cluster IP Address'); ?></label>
            <div class="col-sm-10">
                <input name="frm_cluster_ip" class="form-control" id="frm_cluster_ip" type="text" size="25" value="<?php echo $this->escape( $this->frm_cluster_ip ); ?>" />
                <span class="help-block"><?php echo $this->translate('The IP address of non-DNS SX Clusters.'); ?></span>
            </div>
        </div>
        
    </fieldset>

    <p><button type="submit" class="btn btn-primary"><?php echo $this->translate('Submit!') ?></button> <a class="btn btn-default" href="<?php echo $this->ServerUrl(); ?>/install.php?step=step2"><?php echo $this->translate('Go to previous step...');?></a></p>

</form>
