<?php 
    $pretty_print_rev_hash = function($hash) {
        $hash = substr($hash, 0, strrpos($hash, ':'));
        $hash = substr($hash, 0, strrpos($hash, '.'));
        return $hash;
    }
?>
<div class="wrap">
<h1><?php echo $this->translate('File Revisions'); ?></h1>
<hr/>
<?php if (isset($this->error)): ?>
    <p><?php echo $this->error; ?></p>
<?php else:

    if (isset($this->action_result)) {
        echo '<p>', $this->action_result, '</p><br>',PHP_EOL;
    }

    echo '<p>',sprintf($this->translate('File: <strong>%s</strong>'), $this->escape($this->path)),'</p>',PHP_EOL;
    
    if (empty($this->revisions)) {
        echo '<p>',$this->translate('No revisions found.'),'</p>',PHP_EOL;
    } else {
    
        $has_revisions = (count($this->revisions) > 1);
    echo '<p>',$this->translate('Available revisions (most recent first):'),'</p>',PHP_EOL;

        ?>
        <form action="<?php echo $this->serverUrl(); ?>/revs/<?php echo $this->escape($this->sxUrlEncode($this->path)); ?>" method="post" id="revisions_form">
            <table class="generic_table">
                <tr><th colspan="2"><?php echo $this->translate('Rev.');?></th><th><?php echo $this->translate('Date');?></th><th><?php echo $this->translate('Size');?></th><th><?php echo $this->translate('Actions');?></th></tr>
<?php
                $is_first = TRUE;
                $rev_no = 1;
                $file_type = My_Utils::getFileType($this->path);
                foreach($this->revisions as $rev) {
                    $rev_id = sha1($rev['rev']);
                    ?>
                    
                    <tr><td><?php if ($is_first) { $is_first = FALSE; } else { ?><input type="radio" name="rev_id" value="<?php echo $rev_id; ?>"><?php } ?></td><td><a href="<?php echo $this->serverUrl(); ?>/revdl/<?php echo sha1($rev['rev']),'/', $this->escape($this->sxUrlEncode($this->path)); ?>" title="<?php echo $this->translate( ($file_type == 'data' ? 'Download this revision' : 'Preview this revision' )) ; ?>" <?php if ($file_type != 'data') { echo 'data-filetype="', $file_type,'" class="revpreview"' ; }?> data-rev-id="<?php echo $rev_id; ?>" data-rev-label="<?php echo  $rev_no, ' - ', $this->escape($pretty_print_rev_hash($rev['rev'])); ?>" ><?php printf($this->translate('Rev. %d'), $rev_no); ?></a></td><td><?php echo $pretty_print_rev_hash($rev['rev']);  ?></td><td><?php echo $this->fileSizeFormat($rev['size']); ?></td>
                        <?php if ($file_type !='data'): ?>
                            <td><a href="<?php echo $this->serverUrl(); ?>/revdl/<?php echo sha1($rev['rev']),'/', $this->escape($this->sxUrlEncode($this->path)); ?>" title="<?php echo $this->translate('Download this revision'); ?>"><?php echo $this->translate('Download'); ?></a></td>
                        <?php else: ?> 
                            <td></td>
                        <?php endif;?></tr>
                    <?php
                    $rev_no++;
                }
?>
            </table>
            <p><?php if (count($this->revisions) > 1) { ?><input type="submit" class="styled-button" name="frm_revs_action" value="<?php echo $this->translate('Restore'); ?>"> <?php } ?><a class="styled-button" href="<?php echo $this->serverUrl(); ?>/vol/<?php echo $this->sxUrlEncode($this->file_path); ?>" ><?php echo $this->translate('Cancel'); ?></a></p>
        </form>
<?php
    }
    $this->headScript()->appendFile( $this->serverUrl().'/layouts/skylable/js/revisions.js');
?><script type="application/javascript">
        $(document).ready(function(){
            FileRevisions.assignHandlers();
        });
    </script>
    <div id="dialog"></div>
    <?php
endif; 
?>
</div>