<?php

    echo '<p>',sprintf($this->translate('File: <strong>%s</strong>'), $this->escape(basename($this->path))),'</p>',PHP_EOL;

    $options = array();
    foreach($this->revisions as $rev) {
        $options[sha1($rev['rev'])] = $rev['rev'];
    }
echo '<p>',$this->translate('Available revisions (most recent first):'),'</p>',PHP_EOL;
echo $this->formSelect('rev_id', NULL, '', $options);
echo '<p>',$this->translate('Actions:'),'</p>',PHP_EOL;

?>
<ul>
    <li><input name="revsaction" id="revsaction-copy" value="copy" type="radio"><?php echo $this->translate('Copy to (leave blank to create a new revision of this file):'); ?> <input type="text" name="revs_copy_name" id="revs_copy_name" value="<?php echo $this->escape(basename($this->path)); ?>" onfocus="$('#revsaction-copy').prop('checked', true)"></li>
    <li><input name="revsaction" id="revsaction-delete" value="delete" type="radio"><?php echo $this->translate('Delete the selected revision.'); ?></li>
</ul>
