<?php

    if (isset($this->file_already_shared)) {
        echo '<p><em>',$this->translate('The file is already shared: the password and the expire time will be updated.'),'</em></p><br/>';
    }

    if (isset($this->errors)) {
        echo '<ul><li><strong>',$this->translate('There are errors!'),'</strong></li>';
        echo '<li>',implode('</li><li>', $this->errors),'</li></ul><br/>';
    }
?>
<ul>
    <li><?php printf($this->translate('File: <span>%s</span>'), $this->share_file); ?><input type="hidden" name="path" value="<?php echo $this->escape($this->share_path); ?>" /></li>

    <li class="top-margin"><label><?php echo $this->translate('Expire Time:'); ?></label><?php 
        // Times are in hours
        echo $this->formSelect('share_expire_time', '744', array('class' => 'share-file-expire-time'), array(
            '24' => $this->translate('One Day'),
            '168' => $this->translate('One Week'),
            '336' => $this->translate('Two Weeks'),
            '744' => $this->translate('One Month'),
            '8760000' => $this->translate('Never Expire') // 1000 years
        ));  ?></li>

    <li class="top-margin"><label><?php printf($this->translate('Password (Leave empty if none. Max allowed length is %d characters.)'), 24); ?></label><input class="share-file-link" type="password" name="share_password" value="" placeholder="<?php echo $this->translate('Password'); ?>" /></li>
    <li><input class="share-file-link" type="password" name="share_password_confirm" value="" placeholder="<?php echo $this->translate('Confirm Password'); ?>" /></li>
    
    <li class="more-top-margin"><?php echo $this->translate('Are you sure you want to share the file?'); ?></li>
</ul>
