<div class="wrap">
    <h1><?php echo $this->translate('Settings'); ?></h1>
    <hr />
    <p><a href="<?php echo $this->ServerUrl('/settings/sxdrive'); ?>" title="<?php echo $this->translate('Connect with SXDrive'); ?>"><?php echo $this->translate('Connect with SXDrive'); ?></a></p>
    <p><a href="<?php echo $this->ServerUrl('/settings/preferences'); ?>" title="<?php echo $this->translate('Change preferences for your account'); ?>"><?php echo $this->translate('SXWeb Preferences'); ?></a></p>
    <p><a href="<?php echo $this->ServerUrl('/account_settings'); ?>" title="<?php echo $this->translate('Allows you to change your password'); ?>"><?php echo $this->translate('Change your password'); ?></a></p>
    <p><a href="<?php echo $this->ServerUrl('/settings/volumes'); ?>" title="<?php echo $this->translate('Manage volumes'); ?>"><?php echo $this->translate('Manage volumes'); ?></a></p>
    
</div>