<div class="wrap">
    <h1><?php echo $this->translate('SXWeb Preferences'); ?></h1>
    <hr/>
    <?php

    if ($this->form->hasErrors()) { 
        echo '<div class="styled-form-failure">';
        echo $this->form->renderErrors();
        echo '</div>';
    }

    if (isset($this->show_success)) {
        echo '<p>',$this->translate('Account preferences successfully updated.'),'</p>';    
    }
    
    $attr = $this->form->getAttribs();
    $attr['class'] = 'styled-form';
    echo $this->form('pref_form', $attr, FALSE); 
    ?>
    <p><?php echo $this->formLabel('frm_language', $this->translate('Language')), $this->formSelect('frm_language', $this->form->getValue('frm_language'), NULL, My_BaseAction::getLanguageList()); ?></p>
        <p><label for="frm_file_list_size"><?php echo $this->translate('File list size:'); ?></label><input name="frm_file_list_size" type="text" placeholder="<?php echo $this->translate('File list size'); ?>" value="<?php echo $this->form->getValue('frm_file_list_size'); ?>"></p>
    <p><input class="styled-button" type="submit" id="frm_launch" value="<?php echo $this->translate('Save!'); ?>"></p>
    </form>
</div>