<?php
// Prepare the QR code.
$qr_code_str = Zend_Registry::get('skylable')->get('cluster') . '/?token='.Zend_Auth::getInstance()->getIdentity()->getSecretKey();
$cluster_ip = Zend_Registry::get('skylable')->get('cluster_ip', FALSE);
if (!empty($cluster_port)) {
    $qr_code_str .= '&ip='.strval($cluster_ip);
}

$cluster_ssl = Zend_Registry::get('skylable')->get('cluster_ssl', TRUE);
if (empty($cluster_ssl)) {
    $qr_code_str .= '&ssl=n';
} else {
    $qr_code_str .= '&ssl='.((bool)$cluster_ssl ? 'y' : 'n');
}

$cluster_port = Zend_Registry::get('skylable')->get('cluster_port', FALSE);
if (is_numeric($cluster_port)) {
    $qr_code_str .= '&port='.strval($cluster_port);
}

?>
<div class="wrap">
<h1><?php echo $this->translate('Connect with SXDrive'); ?></h1>
    <hr/>
    <?php 
    if ($this->demoMode()) {
        echo '<h3>',$this->translate('This is a demo: SXDrive cannot be used to access this cluster.'), '</h3>';    
    } 
    ?>
<script src="<?php echo $this->ServerUrl(); ?>/layouts/skylable/js/jquery.qrcode-0.9.4.min.js" type="text/javascript" ></script>
<script type="text/javascript" >
    $(document).ready(function(){
        $("div#qr_code").qrcode({
            render:'div',size: 208,background:'#fff',fill: '#000',
            text: '<?php echo $qr_code_str; ?>'
        });
    });
</script>
<p><?php echo $this->translate('Secret Key:'); ?> <input name="secret_key" type="text" placeholder="<?php echo $this->translate('Secret Key'); ?>" size="70" value="<?php echo $this->escape( Zend_Auth::getInstance()->getIdentity()->getSecretKey() ); ?>"></p>
<p>
    <a class="styled-button" href="<?php echo $this->url( array('controller' => 'settings', 'action' => 'cluster-config'), 'default', TRUE ); ?>" ><?php echo $this->translate('Download SXDrive Cluster Config');?></a></p>
    <hr>
    <h2><?php echo $this->translate('SXDrive downloads'); ?></h2>
    <p><?php echo $this->translate('You can download SXDrive here:'); ?></p>
    <p><a style="margin-right:15px;" href="http://www.skylable.com/download/sxdrive/" onclick="window.open(this.href); return false;"><img src="<?php echo $this->ServerUrl(); ?>/layouts/skylable/images/desktop_app.png"></a>
        <a style="margin-right:15px;" href="http://www.skylable.com/download/sxdrive/android" onclick="window.open(this.href); return false;"><img src="<?php echo $this->ServerUrl(); ?>/layouts/skylable/images/google_play.png"></a>
        <a style="margin-right:15px;" href="http://www.skylable.com/download/sxdrive/ios" onclick="window.open(this.href); return false;"><img src="<?php echo $this->ServerUrl(); ?>/layouts/skylable/images/appstore-button.png"></a></p>
    <hr/>
    <div id="qr">
        <p><?php echo $this->translate('QR Code:'); ?></p><div id="qr_code"></div>
    </div>
    <hr/>
    <p><a class="styled-button" href="<?php echo $this->serverUrl('/settings'); ?>" title="<?php echo $this->translate('Go back to settings...'); ?>"><?php echo $this->translate('Go back to settings...'); ?></a></p>
    </div>
