<div class="wrap">
<h1><?php echo $this->translate('Connect with SXDrive'); ?></h1>
    <hr/>
    <?php 
    if ($this->demoMode()) {
        echo '<h3>',$this->translate('This is a demo: SXDrive cannot be used to access this cluster.'), '</h3>';    
    } 
    ?>
<script src="<?php echo $this->ServerUrl(); ?>/layouts/skylable/js/jquery.qrcode-0.9.4.min.js" type="text/javascript" ></script>
<script type="text/javascript" >
    $(document).ready(function(){
        $("div#qr_android").qrcode({
            render:'div',size: 208,background:'#fff',fill: '#000',
            text: '<?php echo Zend_Registry::get('skylable')->get('cluster') . "/" .Zend_Auth::getInstance()->getIdentity()->getSecretKey();?>'
        });
        $("div#qr_ios").qrcode({
            render:'div',size: 208,background:'#fff',fill: '#000',
            text: '<?php echo Zend_Registry::get('skylable')->get('cluster') . ";token=" .Zend_Auth::getInstance()->getIdentity()->getSecretKey();?>'
        });
    });
</script>
<div id="qr">
    <p><?php echo $this->translate('QR Code for Android:'); ?></p><div id="qr_android"></div>
    <p><?php echo $this->translate('QR Code for iOS:'); ?></p><div id="qr_ios"></div>
</div>
<p><?php echo $this->translate('Secret Key:'); ?> <input name="secret_key" type="text" placeholder="<?php echo $this->translate('Secret Key'); ?>" size="70" value="<?php echo $this->escape( Zend_Auth::getInstance()->getIdentity()->getSecretKey() ); ?>"></p>
<p>
    <a class="styled-button" href="<?php echo $this->url( array('controller' => 'settings', 'action' => 'cluster-config'), 'default', TRUE ); ?>" ><?php echo $this->translate('Download SX Drive Cluster Config');?></a>
    <span class="btn-desc">(You can download SXDrive for Desktop here: <a href="http://cdn.skylable.com/sxdrive/sxdrive-latest.exe">Windows</a> / <a href="http://cdn.skylable.com/sxdrive/sxdrive-latest.dmg">MacOSX</a> / <a href="http://www.skylable.com/download/#sxdrive">Linux</a>)</span>
</p>
    </div>