<div class="wrap">
<?php
/*
    The contents of this file are subject to the Common Public Attribution License
    Version 1.0 (the "License"); you may not use this file except in compliance with
    the License. You may obtain a copy of the License at
    http://opensource.org/licenses/cpal_1.0. The License is based on the Mozilla
    Public License Version 1.1 but Sections 14 and 15 have been added to cover use
    of software over a computer network and provide for limited attribution for the
    Original Developer. In addition, Exhibit A has been modified to be consistent with
    Exhibit B.
    
    Software distributed under the License is distributed on an "AS IS" basis, WITHOUT
    WARRANTY OF ANY KIND, either express or implied. See the License for the
    specific language governing rights and limitations under the License.
    
    The Original Code is the SXWeb project.
    
    The Original Developer is the Initial Developer.
    
    The Initial Developer of the Original Code is Skylable Ltd (info-copyright@skylable.com). 
    All portions of the code written by Initial Developer are Copyright (c) 2013 - 2015
    the Initial Developer. All Rights Reserved.

    Contributor(s):    

    Alternatively, the contents of this file may be used under the terms of the
    Skylable White-label Commercial License (the SWCL), in which case the provisions of
    the SWCL are applicable instead of those above.
    
    If you wish to allow use of your version of this file only under the terms of the
    SWCL and not to allow others to use your version of this file under the CPAL, indicate
    your decision by deleting the provisions above and replace them with the notice
    and other provisions required by the SWCL. If you do not delete the provisions
    above, a recipient may use your version of this file under either the CPAL or the
    SWCL.
*/
if (isset($this->error)) {
    echo '<h1>',$this->translate('Manage Volume'),'</h1>',PHP_EOL;
    echo '<p>',$this->error,'</p>',PHP_EOL;
    echo '<p><a href="',$this->serverUrl('/settings/volumes'),'" class="styled-button">',$this->translate('Go to volume list...'),'</a></p>',PHP_EOL;
} else {
    echo '<h1>',sprintf($this->translate('Manage Volume: %s'), $this->volume),'</h1>',PHP_EOL;
    
    if (isset($this->volume_error)) {
        echo '<p>',$this->escape($this->volume_error),'</p>',PHP_EOL;
        echo '<p><a href="',$this->serverUrl('/settings/volumes'),'" class="styled-button">',$this->translate('Go to volume list...'),'</a></p>',PHP_EOL;
    } else {
        
        echo '<h2>',$this->translate('Volume Info'),'</h2>',PHP_EOL;
        ?><table class="two_column_table">
        <tr><th><?php echo $this->translate('Name'); ?></th><td><a href="<?php echo $this->serverUrl('/vol'),'/',rawurlencode($this->volume); ?>" title="<?php echo $this->translate('Browse the volume...');?>"><?php echo $this->escape($this->volume); ?></a></td></tr>
        <tr><th><?php echo $this->translate('Owner'); ?></th><td><?php echo $this->escape($this->volume_data['owner']); ?></td></tr>
        <tr><th><?php echo $this->translate('Replica'); ?></th><td><?php echo $this->volume_data['replica']; ?></td></tr>
        <tr><th><?php echo $this->translate('Revisions'); ?></th><td><span id="revision-count-item"><?php echo $this->volume_data['revs']; ?></span><?php if ($this->volume_can_manage_revisions): ?> <button class="styled-button" id="change-revisions-btn"><?php echo $this->translate('Change...'); ?></button><?php endif; ?></td></tr>
        <tr><th><?php echo $this->translate('Filter'); ?></th><td><?php echo $this->volume_data['filter']; ?></td></tr>
        <tr><th><?php echo $this->translate('Access'); ?></th><td><?php echo $this->prettifyVolumeAccessRights($this->volume_data['access']); ?></td></tr>
        <tr><th><?php echo $this->translate('Size'); ?></th><td><?php echo $this->fileSizeFormat($this->volume_data['volume_size']); ?></td></tr>
        <tr><th><?php echo $this->translate('Used Space'); ?></th><td><?php echo $this->fileSizeFormat($this->volume_data['used_space']); ?></td></tr>
        </table>
    <?php
        echo '<p><a href="',$this->serverUrl('/settings/volumes'),'" class="styled-button">',$this->translate('Manage another volume...'),'</a></p>',PHP_EOL;

        echo '<hr/><h2>',$this->translate('Volume Access Control List'),'</h2>',PHP_EOL;
        echo '<div><button class="styled-button" onclick="changeUserPermissions(null, true); return false;">',$this->translate('Add user...'),'</button><div id="acl_table_container">',$this->render('/settings/volume_acl_table.phtml'),'</div></div>';
        ?>
        <script type="application/javascript">
            var ajax_is_working = false;
            var the_volume = '<?php echo $this->volume; ?>';

            /**
             * Change user permissions using a modal dialog.
             * @param HTMLElement ctrl the HTML element describing the user
             * @param boolean new_user true add the user, false modify the user from the control
             */
            function changeUserPermissions(ctrl, new_user) {
                if (new_user === true) {
                    var user_name = '';
                } else {
                    var user_name = $(ctrl).data('user');    
                }
                
                if (ctrl) {
                    var permissions = $(ctrl).data('permissions');    
                } else {
                    var permissions = "";
                }

                var dlg = $('#dialog');
                dlg.dialog({
                    autoOpen: false,
                    modal: true,
                    resizable: true,
                    title: Skylable_Lang.managevolumeChangeUserPrivilegesWTitle,
                    beforeClose : function(ev, ui) {
                        return !ajax_is_working;
                    }
                });

                dlg.html(
                    "<ul><li>" + Skylable_Lang.managevolumeChangeUserPrivileges + "</li>" +
                    '<li><input type="text" value="" class="share-file-link" id="frm_username" name="frm_username" /></li>' +
                    '<li>' + Skylable_Lang.managevolumePrivileges + '</li>' +
                    '<li><label><input type="checkbox" name="frm_permissions[]" value="r"'+ (permissions.indexOf("r") == -1 ? "" : ' checked="checked"') +'> ' + Skylable_Lang.managevolumePrivRead + ' </label></li>'+
                    '<li><label><input type="checkbox" name="frm_permissions[]" value="w"'+ (permissions.indexOf("w") == -1 ? "" : ' checked="checked"') +'> ' + Skylable_Lang.managevolumePrivWrite + ' </label></li>'+
                    '<li><label><input type="checkbox" name="frm_permissions[]" value="m"'+ (permissions.indexOf("m") == -1 ? "" : ' checked="checked"') +'> ' + Skylable_Lang.managevolumePrivManager + ' </label></li>'+
                    "</ul>");
                
                $('#frm_username').val(user_name);

                dlg.dialog('option', 'buttons', [
                    {
                        id : "dlg_yes_btn",
                        text : Skylable_Lang.updateBtn,
                        click : function(e) {
                            
                            var permissions = $("input[name='frm_permissions[]']:checked").serialize();
                            if (permissions.length == 0) {
                                permissions= encodeURIComponent("frm_permissions[]");
                            }
                            
                            var the_user = $('#frm_username').val();

                            jQuery.ajax({
                                type:"POST",
                                url:"<?php echo $this->serverUrl('/ajax/managevolume'); ?>",
                                data:"volume="+encodeURIComponent(the_volume)+"&operation=modperm&user=" + encodeURIComponent(the_user) + "&" + permissions,
                                dataType:"json",
                                beforeSend:function(xhr, opt) {
                                    ajax_is_working = true;

                                    dlg.dialog('option', 'buttons', [{
                                        text : Skylable_Lang.closeBtn,
                                        click : function(e) {
                                            dlg.dialog('close');
                                            dlg.dialog('destroy');
                                        }
                                    }]);
                                },
                                complete:function(xhr, status){
                                    ajax_is_working = false;
                                },
                                success:function(data, status, xhr) {
                                    
                                    dlg.html("<p>" + data.message + "</p>");

                                    if (data.status === true) {
                                        $('#acl_table_container').html(data.acl_table);
                                    }
                                },
                                error:function(xhr, status) {
                                    
                                    if (xhr.getResponseHeader('Content-Type') === 'application/json') {
                                        var response_text = JSON.parse(xhr.responseText);
                                        dlg.html("<p>" + response_text.error + "</p>");

                                        if (xhr.status == 403) {
                                            dlg.dialog({
                                                buttons:[{
                                                    text : Skylable_Lang['doLoginBtn'],
                                                    click : function (e) {
                                                        window.location.href = response_text.url;
                                                    }
                                                }]
                                            });
                                        }
                                    } else {
                                        dlg.html(xhr.responseText);
                                    }
                                }
                            });
                        }
                    },
                    {
                        text : Skylable_Lang.cancelBtn,
                        click : function(e) {
                            dlg.dialog('close');
                            dlg.dialog('destroy');

                        }
                    }
                ]);
                
                ajax_is_working = false;
                dlg.dialog('open');
            }
            
            $(document).ready(function(){
                
                // Manage the revision limit change 
                $('#change-revisions-btn').click(function(e){
                    var item = document.getElementById('revision-count-item');
                    
                    // Shows the dialog to change the revision count
                    var dlg = $('#dialog');
                    dlg.dialog({
                        autoOpen: false,
                        modal: true,
                        resizable: true,
                        title: Skylable_Lang.settingsRevisionsLimitWindowTitle,
                        beforeClose : function(ev, ui) {
                            return !ajax_is_working;
                        }
                    });

                    dlg.html('<ul><li>' + Skylable_Lang.settingsRevisionsLimitChangeMessage + '</li><li><input id="new-revision-count" class="share-file-link" type="text" value="'+ item.innerHTML +'"></li></ul>');

                    dlg.dialog('option', 'buttons', [
                        {
                            id : "dlg_yes_btn",
                            text : Skylable_Lang.updateBtn,
                            click : function(e) {

                                var rev_count = $.trim( $('#new-revision-count').val() );
                                
                                jQuery.ajax({
                                    type:"POST",
                                    url:"<?php echo $this->serverUrl('/ajax/managevolume'); ?>",
                                    data:"volume="+encodeURIComponent(the_volume)+"&operation=rev&rev_count="+encodeURIComponent( rev_count ),
                                    dataType:"json",
                                    beforeSend:function(xhr, opt) {
                                        ajax_is_working = true;
                                    },
                                    complete:function(xhr, status){
                                        ajax_is_working = false;
                                    },
                                    success:function(data, status, xhr) {
                                        $('#dlg_yes_btn').hide();
                                        dlg.html("<p>" + data.message + "</p>");
                                        
                                        if (data.status === true) {
                                            item.innerHTML = data.rev_count;
                                        } 
                                    },
                                    error:function(xhr, status) {
                                        $('#dlg_yes_btn').hide();
                                        if (xhr.getResponseHeader('Content-Type') === 'application/json') {
                                            var response_text = JSON.parse(xhr.responseText);
                                            dlg.html("<p>" + response_text.error + "</p>");

                                            if (xhr.status == 403) {
                                                dlg.dialog({
                                                    buttons:[{
                                                        text : Skylable_Lang['doLoginBtn'],
                                                        click : function (e) {
                                                            window.location.href = response_text.url;
                                                        }
                                                    }]
                                                });    
                                            } 
                                        } else {
                                            dlg.html(xhr.responseText);
                                        }
                                    }
                                });
                            }
                        },
                        {
                            text : Skylable_Lang.closeBtn,
                            click : function(e) {
                                dlg.dialog('close');
                                dlg.dialog('destroy');
                                
                            }
                        }
                    ]);

                    dlg.dialog('open');
                    
                    
                });
            });
        </script>
    <?php
    }
}

?></div><div id="dialog"></div>
 