<div class="wrap">
<?php
/*
    The contents of this file are subject to the Common Public Attribution License
    Version 1.0 (the "License"); you may not use this file except in compliance with
    the License. You may obtain a copy of the License at
    http://opensource.org/licenses/cpal_1.0. The License is based on the Mozilla
    Public License Version 1.1 but Sections 14 and 15 have been added to cover use
    of software over a computer network and provide for limited attribution for the
    Original Developer. In addition, Exhibit A has been modified to be consistent with
    Exhibit B.
    
    Software distributed under the License is distributed on an "AS IS" basis, WITHOUT
    WARRANTY OF ANY KIND, either express or implied. See the License for the
    specific language governing rights and limitations under the License.
    
    The Original Code is the SXWeb project.
    
    The Original Developer is the Initial Developer.
    
    The Initial Developer of the Original Code is Skylable Ltd (info-copyright@skylable.com). 
    All portions of the code written by Initial Developer are Copyright (c) 2013 - 2015
    the Initial Developer. All Rights Reserved.

    Contributor(s):    

    Alternatively, the contents of this file may be used under the terms of the
    Skylable White-label Commercial License (the SWCL), in which case the provisions of
    the SWCL are applicable instead of those above.
    
    If you wish to allow use of your version of this file only under the terms of the
    SWCL and not to allow others to use your version of this file under the CPAL, indicate
    your decision by deleting the provisions above and replace them with the notice
    and other provisions required by the SWCL. If you do not delete the provisions
    above, a recipient may use your version of this file under either the CPAL or the
    SWCL.
*/

echo '<h1>',$this->translate('Manage Volumes'),'</h1>',PHP_EOL;

if (isset($this->error)) {
    echo '<p>',$this->error,'</p>',PHP_EOL;
} else {
    if (empty($this->volume_list) || !is_array($this->volume_list)) {
        echo '<p>',$this->translate('No volumes found!'),'</p>',PHP_EOL;
    } else {
        ?>
<table class="generic_table">
    <thead>
    <tr><th><?php echo $this->translate('Name'); ?></th><th><?php echo $this->translate('Owner'); ?></th><th><?php echo $this->translate('Replica'); ?></th><th><?php echo $this->translate('Revisions'); ?></th><th><?php echo $this->translate('Filter'); ?></th><th><?php echo $this->translate('Access'); ?></th><th><?php echo $this->translate('Size'); ?></th><th><?php echo $this->translate('Used Space'); ?></th></tr>
    </thead>
    <tbody>
<?php

        foreach($this->volume_list as $volume) {
            echo '<tr>';
            $v = My_Utils::getRootFromPath($volume['path']);
            echo '<td><a href="',$this->serverUrl('/settings/volume'),'?volume=',rawurlencode($v),'" title="',$this->translate('Manage the volume'),'">',$this->escape($v),'</a></td>';
            echo '<td>',$this->escape($volume['owner']),'</td>';
            echo '<td>',$volume['replica'],'</td>';
            echo '<td>',$volume['revs'],'</td>';
            echo '<td>',$volume['filter'],'</td>';
            echo '<td>',$this->prettifyVolumeAccessRights($volume['access']),'</td>';
            echo '<td>',$this->fileSizeFormat($volume['volume_size']),'</td>';
            echo '<td>',$this->fileSizeFormat($volume['used_space']),'</td>';
            echo '</tr>',PHP_EOL;
        }
        ?>
    </tbody>
</table>
<?php
    }
}
?>
    <p><a class="styled-button" href="<?php echo $this->serverUrl('/settings'); ?>" title="<?php echo $this->translate('Go back to settings...'); ?>"><?php echo $this->translate('Go back to settings...'); ?></a></p>
</div>