<?php

/*
    The contents of this file are subject to the Common Public Attribution License
    Version 1.0 (the "License"); you may not use this file except in compliance with
    the License. You may obtain a copy of the License at
    http://opensource.org/licenses/cpal_1.0. The License is based on the Mozilla
    Public License Version 1.1 but Sections 14 and 15 have been added to cover use
    of software over a computer network and provide for limited attribution for the
    Original Developer. In addition, Exhibit A has been modified to be consistent with
    Exhibit B.
    
    Software distributed under the License is distributed on an "AS IS" basis, WITHOUT
    WARRANTY OF ANY KIND, either express or implied. See the License for the
    specific language governing rights and limitations under the License.
    
    The Original Code is the SXWeb project.
    
    The Original Developer is the Initial Developer.
    
    The Initial Developer of the Original Code is Skylable Ltd (info-copyright@skylable.com). 
    All portions of the code written by Initial Developer are Copyright (c) 2013 - 2015
    the Initial Developer. All Rights Reserved.

    Contributor(s):    

    Alternatively, the contents of this file may be used under the terms of the
    Skylable White-label Commercial License (the SWCL), in which case the provisions of
    the SWCL are applicable instead of those above.
    
    If you wish to allow use of your version of this file only under the terms of the
    SWCL and not to allow others to use your version of this file under the CPAL, indicate
    your decision by deleting the provisions above and replace them with the notice
    and other provisions required by the SWCL. If you do not delete the provisions
    above, a recipient may use your version of this file under either the CPAL or the
    SWCL.
*/


/**
 * FIXME: for compatibility reasons it uses some old code and external
 * variables.
 * 
 * 
 *  Layout parameters:
 * 
 * 'url' - the misleading name of the current viewed path
 * 'disable_sidebar' - don't include the sidebar and the upper bar into the layout
 * 'show_sidebar' - boolean : TRUE sidebar is open, FALSE sidebar is closed
 */

$this->declareVars(
        array(
            'url' => '',
            'disable_sidebar' => FALSE,
            'show_sidebar' => TRUE,
            'cluster' => Zend_Registry::get('skylable')->get('cluster')
        )
);

?><!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<?php echo $this->headTitle(); ?>
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">
<?php echo $this->headMeta(); ?>
<link href="<?php echo $this->ServerUrl(); ?>/layouts/skylable/css/_jqueryui.css" rel="stylesheet" />
<link href="<?php echo $this->ServerUrl(); ?>/layouts/skylable/css/_jqueryuistructure.css" rel="stylesheet" />
<link href="<?php echo $this->ServerUrl(); ?>/layouts/skylable/css/main.css" rel="stylesheet" />
<link href="<?php echo $this->ServerUrl(); ?>/layouts/skylable/css/css.css" rel="stylesheet" />
<?php echo $this->headLink(); ?>
<script src="<?php echo $this->ServerUrl(); ?>/layouts/skylable/js/modernizr.js"></script>
<script src="<?php echo $this->ServerUrl(); ?>/js/jquery.min.js"></script>
    <script src="<?php echo $this->ServerUrl(); ?>/js/sprintf.min.js"></script>
    <script src="<?php echo $this->ServerUrl(); ?>/layouts/skylable/js/lang/<?php echo $this->javascriptTranslation(); ?>"></script>
<script src="<?php echo $this->ServerUrl(); ?>/layouts/skylable/js/jquery.cookie.js"></script>
<script src="<?php echo $this->ServerUrl(); ?>/layouts/skylable/js/jquery-ui.js"></script>
<?php if ($this->disable_sidebar == FALSE): ?>
    <script src="<?php echo $this->ServerUrl(); ?>/js/jquery.slimscroll.min.js"></script>
<script src="<?php echo $this->ServerUrl(); ?>/layouts/skylable/js/placeholder.js"></script>
<script src="<?php echo $this->ServerUrl(); ?>/layouts/skylable/js/scripts.js"></script>
<?php
    endif;
?>
<?php if( $this->canWriteToVolume() ): ?>
<script type="text/javascript" src="<?php echo $this->ServerUrl(); ?>/up/js/jquery.fileupload.js"></script>
<script type="text/javascript" src="<?php echo $this->ServerUrl(); ?>/up/js/jquery.iframe-transport.js"></script>
<?php endif; ?>
<?php echo $this->headScript(), PHP_EOL, $this->headStyle(); ?>
</head>
<body id="main-screen" >
<?php 

if ($this->disable_sidebar == FALSE) {

    try {
        $vol = My_Utils::getRootFromPath($this->url);
        $lielm = $this->action('volmobile', 'index', 'menu', array('vol' => $vol));
    } catch(Exception $e) {
       Zend_Controller_Front::getInstance()->getParam('bootstrap')->getResource('log')->debug('clean.phtml - mobile volume listing exception - '.$e->getMessage()); 
    }
?>
<div class="mobile-header">
    <a href="/logout" id="mobile_logout" title="<?php echo $this->translate('Logout'); ?>"><span class="icon-logout ir"></span><span><?php echo $this->translate('Logout'); ?></span></a>
	<?php if(!empty($lielm)): ?>
	<script type="text/javascript">
	$(function(){
		$('.volume-select select').change(function(){
			window.open("/vol/"+$(this).val(),"_parent");
			});
		});
	</script>
		<div class="volume-select">
		   <select>
			<?php echo $lielm; ?>
		   </select>
		</div>
	<?php endif;?>	
	<?php if(Zend_Auth::getInstance()->hasIdentity()):  ?>
	<a href="javascript:void(0)" class="upload" id="addfile_mobile">
		<span class="icon-upload ir"></span>
		<span><?php echo $this->translate('Upload'); ?></span>
	</a>
	<?php endif; ?>
</div>
<?php 
echo $this->render('sidebar.phtml');

} // The sidebar enabled code.
?>
<div class="drag-drop-wrap<?php echo ($this->show_sidebar === TRUE ? ' sidebar-margin' : ''); // 'show_sidebar' is defined into sidebar.phtml ?>">
<?php echo $this->layout()->content; ?>

<div class="wrap">
	<?php echo $this->render('footer.phtml'); ?>
</div>
</div>
<?php echo $this->inlineScript(); ?>
</body>
</html>